# This is a workflow for the Main-staging branch
name: Main Staging
# Controls when the action will run. Triggers the workflow after Gradle Build when on main-staging
on:
  workflow_run:
    workflows:
      - "Gradle Build"
    branches:
      - main-staging
    types:
      - completed
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    # Set permissions for the job
    permissions:
      contents: write
    # This job only runs if build succeeds
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Format code
    - name: Apply Spotless Formatting
      run: ./gradlew spotlessApply
    # Pushes code to main
    - name: Push now formatted code
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply spotless formatting
        branch: main
  update_submodule:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This job only runs if format succeeds
    needs: format
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Sends a webhook to the parent repo to update submodules
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: Podcakero/GaCo-2026-Testing
          event-type: submodule-update