name: Update submodule on Parent Repo if Build succeeds

on: 
  workflow_run:
    workflows: 
      - "Gradle Build"
    types: 
      - completed
  workflow_dispatch:

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.PAT }}
            repository: Podcakero/GaCo-2026-Testing
            event-type: submodule-update
